# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop\Sidebar\sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 450)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 15)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logo_label = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.logo_label.setFont(font)
        self.logo_label.setStyleSheet("padding-left: 6px")
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_4.addWidget(self.logo_label)
        self.verticalLayout_btn = QtWidgets.QVBoxLayout()
        self.verticalLayout_btn.setSpacing(6)
        self.verticalLayout_btn.setObjectName("verticalLayout_btn")
        self.main_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.main_btn.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.main_btn.setFont(font)
        self.main_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    color: rgb(26, 46, 53); \n"
"    background-color: rgb(240, 240, 240); \n"
"     border-width: 2px;\n"
"     border-radius: 5px;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"    background-color: rgb(255, 115, 92);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/home_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/home_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.main_btn.setIcon(icon)
        self.main_btn.setIconSize(QtCore.QSize(11, 8))
        self.main_btn.setCheckable(True)
        self.main_btn.setChecked(True)
        self.main_btn.setAutoExclusive(True)
        self.main_btn.setAutoRepeatInterval(100)
        self.main_btn.setObjectName("main_btn")
        self.verticalLayout_btn.addWidget(self.main_btn)
        self.booking_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.booking_btn.setMinimumSize(QtCore.QSize(115, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.booking_btn.setFont(font)
        self.booking_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    color: rgb(26, 46, 53); \n"
"    background-color: rgb(240, 240, 240);\n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"    background-color: rgb(255, 115, 92);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/booking_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/booking_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.booking_btn.setIcon(icon1)
        self.booking_btn.setIconSize(QtCore.QSize(11, 11))
        self.booking_btn.setCheckable(True)
        self.booking_btn.setAutoExclusive(True)
        self.booking_btn.setObjectName("booking_btn")
        self.verticalLayout_btn.addWidget(self.booking_btn)
        self.accommodation_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.accommodation_btn.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.accommodation_btn.setFont(font)
        self.accommodation_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    color: rgb(26, 46, 53); \n"
"    background-color: rgb(240, 240, 240);\n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"    background-color: rgb(255, 115, 92);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/room_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/room_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.accommodation_btn.setIcon(icon2)
        self.accommodation_btn.setIconSize(QtCore.QSize(12, 11))
        self.accommodation_btn.setCheckable(True)
        self.accommodation_btn.setAutoExclusive(True)
        self.accommodation_btn.setObjectName("accommodation_btn")
        self.verticalLayout_btn.addWidget(self.accommodation_btn)
        self.services_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.services_btn.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.services_btn.setFont(font)
        self.services_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    color: rgb(26, 46, 53); \n"
"    background-color: rgb(240, 240, 240);\n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"    background-color: rgb(255, 115, 92);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/service_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/service_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.services_btn.setIcon(icon3)
        self.services_btn.setIconSize(QtCore.QSize(11, 8))
        self.services_btn.setCheckable(True)
        self.services_btn.setAutoExclusive(True)
        self.services_btn.setObjectName("services_btn")
        self.verticalLayout_btn.addWidget(self.services_btn)
        self.money_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.money_btn.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.money_btn.setFont(font)
        self.money_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    color: rgb(26, 46, 53); \n"
"    background-color: rgb(240, 240, 240);\n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"    background-color: rgb(255, 115, 92);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/money_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/money_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.money_btn.setIcon(icon4)
        self.money_btn.setIconSize(QtCore.QSize(11, 10))
        self.money_btn.setCheckable(True)
        self.money_btn.setAutoExclusive(True)
        self.money_btn.setObjectName("money_btn")
        self.verticalLayout_btn.addWidget(self.money_btn)
        self.verticalLayout_4.addLayout(self.verticalLayout_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    color: rgb(26, 46, 53); \n"
"    background-color: rgb(240, 240, 240);\n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"    background-color: rgb(255, 115, 92);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon5)
        self.exit_btn.setIconSize(QtCore.QSize(11, 11))
        self.exit_btn.setCheckable(True)
        self.exit_btn.setAutoExclusive(True)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_4.addWidget(self.exit_btn)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 0, 1, 1)
        self.content_widget = QtWidgets.QWidget(self.centralwidget)
        self.content_widget.setObjectName("content_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.content_widget)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem1)
        self.fio_label = QtWidgets.QLabel(self.content_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.fio_label.setFont(font)
        self.fio_label.setObjectName("fio_label")
        self.horizontalLayout_header.addWidget(self.fio_label)
        self.user_btn = QtWidgets.QPushButton(self.content_widget)
        self.user_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.user_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    background-color:rgba(0, 0, 0, 0); \n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"}\n"
"\n"
"QPushButton:checked \n"
"{ \n"
"    color: rgb(255,255, 255); \n"
"}")
        self.user_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/user_gray.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/user_white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.user_btn.setIcon(icon6)
        self.user_btn.setIconSize(QtCore.QSize(15, 15))
        self.user_btn.setCheckable(True)
        self.user_btn.setChecked(False)
        self.user_btn.setAutoRepeat(True)
        self.user_btn.setAutoExclusive(False)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_header.addWidget(self.user_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_header)
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.home_page = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.home_page.setFont(font)
        self.home_page.setAlignment(QtCore.Qt.AlignCenter)
        self.home_page.setObjectName("home_page")
        self.gridLayout_2.addWidget(self.home_page, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.tabWidget.setFont(font)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setVerticalSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_btn = QtWidgets.QPushButton(self.tab_3)
        self.search_btn.setMinimumSize(QtCore.QSize(0, 15))
        self.search_btn.setStyleSheet("QPushButton \n"
"{ \n"
"    background-color:rgba(0, 0, 0, 0); \n"
"    border-width: 2px;\n"
"    border-radius: 5px; \n"
"}")
        self.search_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\Desktop\\Sidebar\\main_view/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon7)
        self.search_btn.setIconSize(QtCore.QSize(15, 15))
        self.search_btn.setCheckable(False)
        self.search_btn.setAutoExclusive(True)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.fio_editor = QtWidgets.QLineEdit(self.tab_3)
        self.fio_editor.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.fio_editor.setFont(font)
        self.fio_editor.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius: 5px; \n"
"padding-left:10px;")
        self.fio_editor.setObjectName("fio_editor")
        self.horizontalLayout.addWidget(self.fio_editor)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_booking = QtWidgets.QGridLayout()
        self.gridLayout_booking.setObjectName("gridLayout_booking")
        self.gridLayout_8.addLayout(self.gridLayout_booking, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setGeometry(QtCore.QRect(10, 10, 404, 44))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.booking_date = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.booking_date.setFont(font)
        self.booking_date.setCalendarPopup(True)
        self.booking_date.setObjectName("booking_date")
        self.verticalLayout.addWidget(self.booking_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.checkin_date = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkin_date.setFont(font)
        self.checkin_date.setStyleSheet("")
        self.checkin_date.setCalendarPopup(True)
        self.checkin_date.setObjectName("checkin_date")
        self.verticalLayout_2.addWidget(self.checkin_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.checkout_date = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.checkout_date.setFont(font)
        self.checkout_date.setCalendarPopup(True)
        self.checkout_date.setObjectName("checkout_date")
        self.verticalLayout_3.addWidget(self.checkout_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.widget1 = QtWidgets.QWidget(self.tab_4)
        self.widget1.setGeometry(QtCore.QRect(10, 60, 301, 42))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.room_description = QtWidgets.QComboBox(self.widget1)
        self.room_description.setMinimumSize(QtCore.QSize(0, 20))
        self.room_description.setObjectName("room_description")
        self.verticalLayout_6.addWidget(self.room_description)
        self.widget2 = QtWidgets.QWidget(self.tab_4)
        self.widget2.setGeometry(QtCore.QRect(11, 131, 271, 121))
        self.widget2.setObjectName("widget2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.room_type_title = QtWidgets.QLabel(self.widget2)
        self.room_type_title.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.room_type_title.setFont(font)
        self.room_type_title.setObjectName("room_type_title")
        self.verticalLayout_7.addWidget(self.room_type_title)
        self.room_type_editor = QtWidgets.QLineEdit(self.widget2)
        self.room_type_editor.setReadOnly(True)
        self.room_type_editor.setObjectName("room_type_editor")
        self.verticalLayout_7.addWidget(self.room_type_editor)
        self.gridLayout_9.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.room_price_title = QtWidgets.QLabel(self.widget2)
        self.room_price_title.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.room_price_title.setFont(font)
        self.room_price_title.setObjectName("room_price_title")
        self.verticalLayout_8.addWidget(self.room_price_title)
        self.room_price_editor = QtWidgets.QLineEdit(self.widget2)
        self.room_price_editor.setReadOnly(True)
        self.room_price_editor.setObjectName("room_price_editor")
        self.verticalLayout_8.addWidget(self.room_price_editor)
        self.gridLayout_9.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.room_capacity_title = QtWidgets.QLabel(self.widget2)
        self.room_capacity_title.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.room_capacity_title.setFont(font)
        self.room_capacity_title.setObjectName("room_capacity_title")
        self.verticalLayout_9.addWidget(self.room_capacity_title)
        self.room_capacity_editor = QtWidgets.QLineEdit(self.widget2)
        self.room_capacity_editor.setStyleSheet("")
        self.room_capacity_editor.setReadOnly(True)
        self.room_capacity_editor.setObjectName("room_capacity_editor")
        self.verticalLayout_9.addWidget(self.room_capacity_editor)
        self.gridLayout_9.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.room_balcony_title = QtWidgets.QLabel(self.widget2)
        self.room_balcony_title.setMaximumSize(QtCore.QSize(16777215, 15))
        self.room_balcony_title.setObjectName("room_balcony_title")
        self.verticalLayout_10.addWidget(self.room_balcony_title)
        self.room_balcony_editor = QtWidgets.QLineEdit(self.widget2)
        self.room_balcony_editor.setReadOnly(True)
        self.room_balcony_editor.setObjectName("room_balcony_editor")
        self.verticalLayout_10.addWidget(self.room_balcony_editor)
        self.gridLayout_9.addLayout(self.verticalLayout_10, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.living_page = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.living_page.setFont(font)
        self.living_page.setAlignment(QtCore.Qt.AlignCenter)
        self.living_page.setObjectName("living_page")
        self.gridLayout_4.addWidget(self.living_page, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.service_page = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.service_page.setFont(font)
        self.service_page.setAlignment(QtCore.Qt.AlignCenter)
        self.service_page.setObjectName("service_page")
        self.gridLayout_5.addWidget(self.service_page, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.money_page = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.money_page.setFont(font)
        self.money_page.setAlignment(QtCore.Qt.AlignCenter)
        self.money_page.setObjectName("money_page")
        self.gridLayout_7.addWidget(self.money_page, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.user_page = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.user_page.setFont(font)
        self.user_page.setAlignment(QtCore.Qt.AlignCenter)
        self.user_page.setObjectName("user_page")
        self.gridLayout_6.addWidget(self.user_page, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.content_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        self.exit_btn.clicked.connect(MainWindow.close) # type: ignore
        self.user_btn.clicked.connect(self.main_btn.repaint) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff735c;\">H</span><span style=\" font-weight:600;\">otelChain</span></p></body></html>"))
        self.main_btn.setText(_translate("MainWindow", "Главная"))
        self.booking_btn.setText(_translate("MainWindow", "Бронирование"))
        self.accommodation_btn.setText(_translate("MainWindow", "Проживание"))
        self.services_btn.setText(_translate("MainWindow", "Услуги"))
        self.money_btn.setText(_translate("MainWindow", "Оплата"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
        self.fio_label.setText(_translate("MainWindow", "Иванов Иван Иванович"))
        self.home_page.setText(_translate("MainWindow", "<html><head/><body><p>Главная страница</p></body></html>"))
        self.fio_editor.setPlaceholderText(_translate("MainWindow", "Поиск..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Все брони"))
        self.label_3.setText(_translate("MainWindow", "Дата бронирования"))
        self.label.setText(_translate("MainWindow", "Дата заезда"))
        self.label_2.setText(_translate("MainWindow", "Дата выезда"))
        self.label_4.setText(_translate("MainWindow", "Вид номера"))
        self.room_type_title.setText(_translate("MainWindow", "Тип номера"))
        self.room_type_editor.setText(_translate("MainWindow", "Тип номера"))
        self.room_price_title.setText(_translate("MainWindow", "Стоимость"))
        self.room_price_editor.setText(_translate("MainWindow", "Стоимость"))
        self.room_capacity_title.setText(_translate("MainWindow", "Вместимость"))
        self.room_capacity_editor.setText(_translate("MainWindow", "Вместимость"))
        self.room_balcony_title.setText(_translate("MainWindow", "Балкон"))
        self.room_balcony_editor.setText(_translate("MainWindow", "Балкон"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Добавить бронь"))
        self.living_page.setText(_translate("MainWindow", "Страница проживания"))
        self.service_page.setText(_translate("MainWindow", "Страница услуг"))
        self.money_page.setText(_translate("MainWindow", "Страница оплаты"))
        self.user_page.setText(_translate("MainWindow", "Страница работника"))
